base_images:
  base:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
  registration:
    name: "4.5"
    namespace: open-cluster-management
    tag: registration
  registration-operator:
    name: "4.5"
    namespace: open-cluster-management
    tag: registration-operator
  registration-operator-src:
    name: "4.5"
    namespace: open-cluster-management
    tag: registration-operator-src
  work:
    name: "4.5"
    namespace: open-cluster-management
    tag: work
binary_build_commands: GOFLAGS="" go build ./cmd/manager
build_root:
  image_stream_tag:
    name: builder
    namespace: open-cluster-management
    tag: go1.14-linux-amd64
images:
- dockerfile_path: build/Dockerfile
  from: base
  inputs:
    bin:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/open-cluster-management/rcm-controller/rcm-controller
  to: latest
promotion:
  name: rcm-controller
  namespace: open-cluster-management
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- artifact_dir: /tmp/artifacts
  as: sonar
  commands: GOPROXY="proxy.golang.org,direct" GOFLAGS="" go help build
  container:
    from: src
  secrets:
  - mount_path: /etc/sonarcloud/
    name: acm-sonarcloud-token
zz_generated_metadata:
  branch: prow-experiment
  org: open-cluster-management
  repo: rcm-controller
