base_images:
  base:
    name: "4.5"
    namespace: ocp
    tag: base
  registration:
    name: "4.5"
    namespace: open-cluster-management
    tag: registration
  registration-operator:
    name: "4.5"
    namespace: open-cluster-management
    tag: registration-operator
  registration-operator-src:
    name: "4.5"
    namespace: open-cluster-management
    tag: registration-operator
  work:
    name: "4.5"
    namespace: open-cluster-management
    tag: work
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
images:
- dockerfile_path: build/Dockerfile
  from: base
  to: rcm-controller
promotion:
  name: "4.5"
  namespace: open-cluster-management
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.4"
  namespace: ocp
tests:
- as: build
  commands: |
    true
  container:
    from: bin
- as: unit
  commands: make test
  container:
    from: bin
zz_generated_metadata:
  branch: master
  org: open-cluster-management
  repo: rcm-controller
